### PR TITLE
Add option to skip non-forge mods.

### PR DESCRIPTION
**Pull request by isXander**
Prevents FML from adding non-mods to classpath.
Configurable through forge general settings.

### CODE REVIEW

**Comment by dreamhopping** [comment]
This could conflict with libraries that need to be put in the mods folder, f.ex: PlayerAPI

**Comment by asbyth** [comment]
> 
> 
> This could conflict with libraries that need to be put in the mods folder, f.ex: PlayerAPI

People should be using AccessTransformers by now, we're not in the times where AT's don't exist and haven't been for awhile. I've not heard of any other mods that do such thing, so I'd say this is pretty safe to go through with (along with the fact that it can be toggled & is off by default)

**Comment by dreamhopping** [comment]
> 
> 
> > This could conflict with libraries that need to be put in the mods folder, f.ex: PlayerAPI
> 
> People should be using AccessTransformers by now, we're not in the times where AT's don't exist and haven't been for awhile. I've not heard of any other mods that do such thing, so I'd say this is pretty safe to go through with (along with the fact that it can be toggled & is off by default)

I guess, PlayerAPI was just an example though. Some sort of warning should be shown to the user before enabling it or in the tooltip or something to highlight that this could break mods that use shared libraries in the mods folder.

**Comment by asbyth** [comment]
> 
> 
> > People should be using AccessTransformers by now, we're not in the times where AT's don't exist and haven't been for awhile. I've not heard of any other mods that do such thing, so I'd say this is pretty safe to go through with (along with the fact that it can be toggled & is off by default)
> 
> I guess, PlayerAPI was just an example though. Some sort of warning should be shown to the user before enabling it or in the tooltip or something to highlight that this could break mods that use shared libraries in the mods folder.

Definitely. Maybe worded like "(This could prevent libraries such as PlayerAPI from loading, which some mods may depend on)."

**Comment by dreamhopping** [comment]
>
> Definitely. Maybe worded like "(This could prevent libraries such as PlayerAPI from loading, which some mods may depend on)."

Sounds good to me :smile:

**Comment by isXander** [comment]
👍

**Pull request merged**
